source 'https://cdn.cocoapods.org/'
source 'https://github.com/Artsy/Specs.git'
platform :ios, '17.0'
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "17.0"
     end
  end
end

target 'gotuda' do
use_frameworks!
	pod 'ReSwift'
	pod 'Moya'
	pod 'ReSwiftThunk'
	pod 'Moya-ObjectMapper'
	pod 'ObjectMapper'
	pod 'Moya/RxSwift'
	pod 'Moya-ObjectMapper/RxSwift'
	pod 'SwiftUI-Shimmer', :git => 'https://github.com/markiv/SwiftUI-Shimmer.git'
end