name: gotuda
options:
    bundleIdPrefix: ru
targets:
    gotuda:
        type: application
        platform: iOS
        settings:
            base:
                MARKETING_VERSION: 1.0
                CURRENT_PROJECT_VERSION: 1
        sources:
            - gotuda
